version: '3'

services:
 robo-friends:
  build: .
  command: npm start
  ports:
   - 3000:3000

 watchtower:
  image: containrrr/watchtower
  environment:
   - WATCHTOWER_POLL_INTERVAL=10 # Poll every 60 seconds
   - WATCHTOWER_MONITOR_ONLY=true
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  container_name: watchtower
